### ISSUE TITLE
Player 2 locked in terminal

### ISSUE THREAD

**Issue by Sourceshard** [AdalynBlack/Loadstone#2]
When adding LoadStone to my mod pack and playing a 2-player steam session. The second player is unable to leave the Terminal.

Here are his logs. Async is mentioned as all my logs are run through it.
[message (13).txt](https://github.com/AdalynBlack/Loadstone/files/14661451/message.13.txt)

**Comment by AdalynBlack** [comment]
So here's what I've figured out so far

The error itself *appears* to be coming from GeneralImprovements, but it seems like that's only because it's failing to notice that the player it's trying to reference doesn't exist

The mod "Oxygen" tries to access the same reference earlier on, and does note that the player script is null for some unknown reason

I'd recommend seeing if GeneralImprovements has any updates, or see if uninstalling it fixes the issue. I'll keep looking to see if I can find the root cause of the issue

**Comment by AdalynBlack** [comment]
As for the references to "Async", those are coming from the "AsyncLoggers" mod
It looks like the logger itself might be erroring in a way that prevents the terminal from being quit successfully

**Comment by AdalynBlack** [comment]
If the issue persists, it would help if you could provide a profile code so that I can have identical mods and configuration settings for testing

**Comment by AdalynBlack** [comment]
Oh! I think I found the issue. It's a [known incompatibility](https://github.com/NotAtomicBomb/TerminalApi/tree/main?tab=readme-ov-file#have-the-glowstick-mod-and-are-unable-to-leave-the-terminal-try-this) between the glowsticks mod and TerminalAPI

**Comment by Sourceshard** [comment]
I am testing out some additions to my pack right now. When I am done I will clean it up and send you it as it was.

**Comment by Sourceshard** [comment]
> Oh! I think I found the issue. It's a [known incompatibility](https://github.com/NotAtomicBomb/TerminalApi/tree/main?tab=readme-ov-file#have-the-glowstick-mod-and-are-unable-to-leave-the-terminal-try-this) between the glowsticks mod and TerminalAPI

This problem is the same outcome as that glitch. 
However, I do not have the Glowsticks mod.
It could be that as soon as LoadStone is installed this event happens to occur again. 

However, with LoadStone deactivated the error does not occur. Re-enabling Loadstone has the event happen reliably.

I will have the modpack code soon.

**Comment by AdalynBlack** [comment]
oh
well, either way, I just tested it out with a friend, and after enabling my mod, neither of us were able to get the terminal glitch to happen
we were both able to exit just fine

**Comment by AdalynBlack** [comment]
I just added a new feature which might help with figuring out the root cause of the issue
the mod will now produce logs when it detects that both it and another mod have modified the same code, and gives me enough information to tell exactly what parts of both mods to look into to find the source of the issue
